version: '3.4'

services:
  myeats.api:
    image: ${DOCKER_REGISTRY-}myeatsapi
    build:
      context: .
      dockerfile: src/MyEats.Api/Dockerfile
    ports:
      - 5400:80
      - 5401:443
    depends_on:
      - sqlserver
  
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "westwing1"
      ACCEPT_EULA: "Y"
    volumes:
      - "./data-mssql:/var/opt/mssql"
    ports:
      - 5050:1433